version: '3.8'

services:
  #database section
  
  #assetdb: sql server
  assetdb:
    container_name: assetdb
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data # sqlserver_data:/var/opt/mssql
    ports:
      - "1435:1433"