version: '3.8'

services:
  #database section
  assetdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

#network section
networks:
  default:
    name: cmms
    driver: bridge

#volumes section
volumes:
  sqlserver_data:
    name: sqlserver_data